# Generated by Django 2.2.6 on 2019-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_detail',
            fields=[
                ('movie_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('center', models.CharField(max_length=12000)),
                ('introduction', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'movie_details',
            },
        ),
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=50)),
                ('mphoto', models.CharField(max_length=500)),
                ('score', models.FloatField()),
                ('url', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'movielist',
            },
        ),
    ]
