# Generated by Django 2.2.6 on 2019-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_short',
            fields=[
                ('movie_short_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_details_id', models.IntegerField(max_length=3)),
                ('username', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=200)),
                ('comment_time', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'movie_short',
            },
        ),
    ]
