# Generated by Django 2.2.6 on 2019-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_movie_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_actor',
            fields=[
                ('movie_actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_details_id', models.IntegerField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movie_actor',
            },
        ),
    ]
