# Generated by Django 2.2.6 on 2019-10-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_movie_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movie_user',
            },
        ),
    ]
